title: Peter Crabbe's Homepage
logo: https://www.arkwolf.com/wp-content/uploads/2019/09/arklogo.png
email: webmail@arkwolf.com
description: >- # this means to ignore newlines until "baseurl:"
  Just another dev blog, about dev things.
baseurl: "" 
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: MajorArkwolf
github_username:  MajorArkwolf

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme 
  - jekyll-feed
  